# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Lunet_config = debug

else ifeq ($(config),release)
  Lunet_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Lunet

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Lunet:
ifneq (,$(Lunet_config))
	@echo "==== Building Lunet ($(Lunet_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(Lunet_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Lunet"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"